Software-Engineering-II-Gruppe2/WebSocket-Server

src/main/java/at/aau/serg/monopoly/websoket/GameWebSocketHandler.java, src/main/java/model/Dice.java, src/main/java/model/DiceManager.java, src/main/java/model/DiceManagerInterface.java, src/main/java/model/Test.java, src/test/java/model/DiceTest.java
This pull request adds a new dice rolling feature to our multiplayer Monopoly game. The changes include:
- Created a new interface
- Concrete implementation of the DiceManager Interface
- The implementation simulates rolling two dice (values between 1 and 6) and returns their sum.
- Modified GameWebSocketHandler.java to integrate the dice rolling feature.
- When a player sends the message "Roll", the handler now calls diceManager.rollDices() and broadcasts the result to all connected clients.
- Added tests to validate all added features
=> Added a feature to roll the dice

src/main/java/at/aau/serg/websocketdemoserver/controller/SoundController.java, src/test/java/at/aau/serg/controller/SoundControllerTest.java
Api erstellt und Test implementiert
=> API für Soundcontroll erstellt und Test implementiert.

src/main/java/at/aau/serg/websocketdemoserver/controller/BrightnessController.java, src/test/java/at/aau/serg/controller/BrightnessControllerTest.java
=> Helligkeitsauswahl nach login

src/main/java/at/aau/serg/monopoly/websoket/GameWebSocketHandler.java, src/main/java/at/aau/serg/websocketdemoserver/controller/SoundController.java, src/test/java/at/aau/serg/controller/SoundControllerTest.java, src/test/java/model/DiceTest.java, src/test/java/model/GameTest.java
Removed code smells suggested by Sonarcloud.
=> reducing-code-smells

src/main/java/at/aau/serg/monopoly/websoket/GameWebSocketHandler.java, src/main/java/model/Game.java, src/test/java/at/aau/serg/monopoly/websoket/GameWebSocketHandlerUnitTest.java, src/test/java/model/GameTest.java
Der aktuelle Spielzustand wird an alle verbundenen Clients gesendet
Methode zum Aktualisieren des Spielergeldes implementiert
Verarbeitung der Geldaktualisierung implementiert
Eingehende Geldänderungen werden nun korrekt verarbeitet und an alle Spieler kommuniziert.
=> (start) geld pro spieler in der spielübersicht anzeigen #124

src/main/java/at/aau/serg/monopoly/websoket/GameWebSocketHandler.java, src/main/java/data/DiceRollMessage.java, src/test/java/at/aau/serg/monopoly/websoket/GameWebSocketHandlerUnitTest.java, src/test/java/model/DiceTest.java
This PR updates the server-side logic for the dice-rolling mechanism.
___
- The dice-roll messages are now sent in JSON format
- Updated the dice-roll logic so that it works without having access to the log in the lobby
- Added Unit-Tests for the newly implemented functionality
=> Update dice logic (server-side)

src/main/java/at/aau/serg/monopoly/websoket/PropertyTransactionService.java, src/main/java/model/properties/BaseProperty.java, src/main/java/model/properties/HouseableProperty.java, src/main/java/model/properties/TrainStation.java, src/main/java/model/properties/Utility.java, src/main/resources/propertyData.json, src/test/java/at/aau/serg/monopoly/websoket/PropertyTransactionServiceTest.java, src/test/java/model/PropertyTest.java
feat: Property-Kauf-System serverseitig
Was ist neu:
- Properties kaufen
- Prüfung ob man genug Geld hat
- Prüft ob man auf dem richtigen Feld steht
- Prüft ob das Property noch frei ist
=> 146 grundstücke kaufen weitere implementierung

src/main/java/at/aau/serg/monopoly/websoket/GameWebSocketHandler.java, src/main/java/model/Game.java, src/test/java/at/aau/serg/monopoly/websoket/GameWebSocketHandlerTest.java, src/test/java/at/aau/serg/monopoly/websoket/GameWebSocketIntegrationTest.java, src/test/java/model/GameTest.java
dieser PR fügt hinzu:
Implementierung des GO-Passing/ Über Los Bonus Feature
-Automatische Addition von 200€ beim Passieren von GO
=> 167 server über los spieler erhält 200

src/main/java/at/aau/serg/monopoly/websoket/GameWebSocketHandler.java, src/main/java/data/DiceRollMessage.java, src/test/java/at/aau/serg/monopoly/websoket/GameWebSocketHandlerDiceTest.java
Der Spieler kann jetzt alternativ selbst die Würfelzahl von 1-39 bestimmen.
=> Game cheat wuerfelzahl selbst bestimmen #170

.github/workflows/build.yml, src/main/java/model/Game.java, src/test/java/at/aau/serg/monopoly/websoket/GameWebSocketIntegrationTest.java
This PR fixes the test that caused the quality gate to fail, although it passed locally.
___
- Added a branch to the workflow to trigger it
- Updated the test so it doesn't fail in the quality gate
- Fixed some intermittent errors that wrote error messages to the log but didn't cause the test to fail
- After inspecting the result, the branch was removed again
=> Fix test that causes the quality gate to fail

pom.xml, src/main/java/at/aau/serg/monopoly/websoket/GameHistoryService.java, src/main/java/at/aau/serg/monopoly/websoket/GameWebSocketHandler.java, src/test/java/at/aau/serg/monopoly/websoket/GiveUpWebSocketHandlerTest.java
Added the feature "Give Up" and connected it to the Server so that everything is logged.
=> On give up branch server

src/test/java/at/aau/serg/monopoly/websoket/GameWebSocketHandlerTest.java
In diesem PR wurden zusätzliche Tests für die Propertylogik ergänzt, um die Coverage zu verbessern
=> Additional tests for improved code coverage

src/main/java/at/aau/serg/monopoly/websoket/GameWebSocketHandler.java, src/test/java/at/aau/serg/monopoly/websoket/GameWebSocketHandlerIntegrationTest.java
The App logs information. Please ensure that sensitive information is never logged. --> comments hinzugefügt zu den gewollten logs die angeschlagen hatten beim mobsf report
=>  bewusst geloggte messages markiert

src/main/java/at/aau/serg/monopoly/websoket/GameWebSocketHandler.java
=> Fixed the Give-up Bug

src/main/java/at/aau/serg/monopoly/websoket/GameWebSocketHandler.java, src/main/java/model/Game.java, src/test/java/model/GameTest.java
This PR improves the `removePlayer(...)` method in `Game.java` and adds some small changes needed for the join button on the app. Of course I also added Unit Tests ;)
___
- Added a game state broadcast after a player disconnects from the server
- Improved the removePlayer(...) method to make it more robust
- Added Unit tests for the new method
=> Changes on the server to improve the Join Button on the client

src/main/java/at/aau/serg/monopoly/websoket/GameWebSocketHandler.java, src/main/java/model/Game.java, src/main/java/model/Player.java, src/main/java/model/PlayerInfo.java, src/main/java/model/cards/MoveCard.java, src/test/java/at/aau/serg/monopoly/websoket/GameWebSocketHandlerTest.java, src/test/java/model/GameTest.java, src/test/java/model/PlayerTest.java, src/test/java/model/cards/MoveCardTest.java
added logic for bringing a player into the prison and the part that holds the player in prison till his time in prison ends Rounds later
=> Gefaengnis aussetzen

src/main/java/at/aau/serg/monopoly/websoket/GameWebSocketHandler.java, src/main/java/at/aau/serg/monopoly/websoket/PropertyTransactionService.java, src/main/java/data/SellPropertyMessage.java, src/test/java/at/aau/serg/monopoly/websoket/GameWebSocketHandlerSellTest.java, src/test/java/at/aau/serg/monopoly/websoket/PropertyTransactionServiceTest.java
Dieser PR fügt die Möglichkeit hinzu, Grundstücke an die Bank zu verkaufen.
Neue Klasse: SellPropertyMessage
WebSocket-Handling für "SELL_PROPERTY"
Spieler erhalten 50 % des Kaufpreises zurück
=> 250 user pay server grundstück verkaufenv2

src/main/java/at/aau/serg/monopoly/websoket/GameWebSocketHandler.java, src/test/java/at/aau/serg/monopoly/websoket/GameWebSocketHandlerEndGameTest.java, src/test/java/at/aau/serg/monopoly/websoket/GameWebSocketHandlerGiveUpTest.java, src/test/java/at/aau/serg/monopoly/websoket/GameWebSocketHandlerPullTest.java
This PR adds the server side changes needed to have a "real" game end. From now on a player gives up if the net value (mortgage value of all owned properties + money) is 0.
**The helper methods should not be in the Handler class itself. BUT: Refactoring will be done anyways in the future so why not at this point.**
___
- Refactored the giveUp-method to reuse it
- Added helper methods for checking the net value of a player
- Added isBankrupt calls where needed
=> Game end: server side

src/main/java/at/aau/serg/monopoly/firebase/LeaderboardService.java, src/main/java/at/aau/serg/monopoly/websoket/GameHistoryService.java, src/main/java/at/aau/serg/monopoly/websoket/GameWebSocketHandler.java, src/main/java/model/GameHistory.java, src/test/java/at/aau/serg/monopoly/websoket/GameHistoryServiceTest.java
für Spieler die aufgegeben haben und den Gewinner
=> Game history update after defined game end

src/main/java/at/aau/serg/monopoly/websoket/GameWebSocketHandler.java, src/main/java/data/ShakeMessage.java, src/test/java/at/aau/serg/monopoly/websoket/GameWebSocketHandlerDiceTest.java
This PR **_FINALLY_** adds the possibility to roll the dice by shaking the device.
___
- An incoming SHAKE MESSAGE from the client is parsed and the dice rolling mechanism is triggered
- Added a DTO for the message
- Refactored the dice roll method to make it more reuseable
=> Device shaking triggers dice roll mechanic: Server side

src/main/java/at/aau/serg/monopoly/websoket/GameWebSocketHandler.java, src/test/java/at/aau/serg/monopoly/websoket/GameWebSocketHandlerUnitTest.java
This PR adds the functionality to kick players. To do that just write a text message in the In-Game-Chat with `KICK $PLAYER_NAME` where `$PLAYER_NAME` denotes the name of the player to be kicked as it is set by the player himself in the profile page.
___
- Added a new message parsing
- Updated existing tests
- FIXED ANOTHER FUCKING SONAR ISSUE BECAUSE SONAR THINKS MY CODE IS NOT RELIABLE - I HOPE ITS RELIABLE ENOUGH FOR YOU NOW !!!!
=> Feature: Kick players

src/test/java/at/aau/serg/monopoly/firebase/UserStatisticsServiceTest.java
Added some tests do increase coverage of this class.
=> User statistics tests

src/main/java/at/aau/serg/monopoly/websoket/RentCalculationService.java, src/main/java/model/properties/BaseProperty.java, src/main/java/model/properties/HouseableProperty.java, src/main/java/model/properties/TrainStation.java, src/main/java/model/properties/Utility.java, src/test/java/at/aau/serg/monopoly/websoket/GameWebSocketHandlerRentTest.java, src/test/java/at/aau/serg/monopoly/websoket/GameWebSocketHandlerTest.java, src/test/java/at/aau/serg/monopoly/websoket/RentCalculationServiceTest.java, src/test/java/model/UtilityTest.java
// fixme use polymorphism in src/main/java/at/aau/serg/monopoly/websoket/RentCalculationService.java implementiert
test zur eröhung der code coverage hinzugefügt
=> Fix sonar issue, add tests and implement fixme

src/main/java/at/aau/serg/monopoly/websoket/GameWebSocketHandler.java, src/main/java/at/aau/serg/monopoly/websoket/RentCalculationService.java, src/test/java/at/aau/serg/monopoly/firebase/FirebaseServiceTest.java, src/test/java/at/aau/serg/monopoly/firebase/LeaderboardServiceTest.java, src/test/java/at/aau/serg/monopoly/firebase/UserStatisticsServiceTest.java
Fixed some sonar issues, will fix more tomorrow (aka today) :)
=> Tests and some Sonar Issues

src/main/java/at/aau/serg/monopoly/websoket/RentCalculationService.java, src/main/java/model/properties/BaseProperty.java, src/main/java/model/properties/HouseableProperty.java, src/main/java/model/properties/TrainStation.java, src/main/java/model/properties/Utility.java, src/test/java/at/aau/serg/monopoly/websoket/GameWebSocketHandlerRentTest.java, src/test/java/at/aau/serg/monopoly/websoket/RentCalculationServiceTest.java, src/test/java/model/UtilityTest.java
Dier PR soll die Implementierung von "Fix sonar issue, add tests and implement fixme #75" wiederherstellen.
=> 82 implement fixme in rentcalculationservice remove sonar issue and add tests
